### ISSUE TITLE
Markdown code spans in description properties gets escaped and therefore not properly rendered in the output

### ISSUE THREAD

**Issue by quadrrem** [Neoteroi/essentials-openapi#24]
The OpenApiSpecification allows for [rich text formatting](https://spec.openapis.org/oas/v3.0.3#rich-text-formatting) in `description` fields using [CommonMark Spec](https://spec.commonmark.org/0.27/). This works well, except when using `code spans`. 

If a `code span` is used to display some json structure the quotation marks (") around the properties get escaped and therefore not properly rendered in the final markdown file.

For example when executing the following command using the example specification
```yaml
openapi: "3.0.2"
info:
  title: API Title
  description: |
    **Response**

    ```json
    [
      {
        "a": "b",
        "c": {
          "d": "e"
        }
      }
    ]
    ```
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
```

`oad gen-docs -s example-openapi.yaml -d test.md --style "MKDOCS"`


the following `code span` in the `description` of the specification

```json
    [
      {
        "a": "b",
        "c": {
          "d": "e"
        }
      }
    ]
```

looks like this in the `test.md` output

```json
[
  {
    &#34;a&#34;: &#34;b&#34;,
    &#34;c&#34;: {
      &#34;d&#34;: &#34;e&#34;
    }
  }
]
```

My guess is that is related to [Jinja autoescape](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.select_autoescape) used here https://github.com/Neoteroi/essentials-openapi/blob/main/openapidocs/mk/jinja.py#L77

Maybe it could be resolved by disabling auto escaping for the description sections, using this https://jinja.palletsprojects.com/en/3.1.x/templates/#autoescape-overrides. But not sure if this could lead to other issues down the road.

**Comment by RobertoPrevato** [comment]
Hi @quadrrem 
Sorry for replying so late. Thank You for reporting this issue, you are absolutely right that it might be resolved in the way you say. The library is already supposed to be used only with trusted sources of OpenAPI specification files.

I try to look into this this weekend.

**Comment by RobertoPrevato** [comment]
Thanks again @quadrrem  for reporting this issue. Finally I was focused on my web frameworks in the last (several) weeks and I postponed this fix.

I corrected this yesterday, with https://pypi.org/project/essentials-openapi/1.0.6/
